### ISSUE TITLE
Strange mouse behaviour

### ISSUE THREAD

**Issue by lucascoelho07** [dhewm/dhewm3#421]
Mouse movement is not properly detected when moving too fast (is like using a low polling rate)

**Comment by DanielGibson** [comment]
Can you provide more information, like what operating system and which mouse you're using?

And do you feel like the game itself slows down/gets laggy or is it "just" that mouse input doesn't feel responsive?

If you open the console (Shift+Esc) and enter `com_showFPS 1` and close it again (Shift+Esc), the game will show the current framerate in the upper right corner - if it drops when moving the mouse, that's an indicator the whole game is slowing down.

**Comment by DanielGibson** [comment]
any update on this?

**Comment by lucascoelho07** [comment]
Sorry for taking too long to answer
I'm on Manjaro Linux and my mouse is a Logitech G 203 Lightsync.
The game itself seems to run fine, it is just the mouse that feels really weird when I move it too fast.

**Comment by DanielGibson** [comment]
IIRC there is/was a bug in SDL with >= 1000Hz mice, but it should be fixed in their current git code **which has not been part of a proper release yet**.

Can you build SDL2 yourself from the current git code and see if your mouse works better when using that?
The code is at https://github.com/libsdl-org/SDL
You can download it as a ZIP archive at https://github.com/libsdl-org/SDL/archive/refs/heads/main.zip

**Comment by lucascoelho07** [comment]
Do I need to do anything else after building and installing it? If not than the problem persists

**Comment by DanielGibson** [comment]
At startup the first thing dhewm3 prints is something like
`dhewm3 1.5.2pre.1305-debug linux-x86_64 Nov 21 2021 03:07:41 using SDL v2.0.10` - if installing it was successful, it should probably print SDL v2.0.17

**Comment by lucascoelho07** [comment]
yeah, it says `dhewm3 1.5.1.1305 linux-x86_64 Sep 17 2021 02:31:46 using SDL v2.0.16`, I'm not sure, but I think this is the one that was already

**Comment by DanielGibson** [comment]
Yes, that's the old one - I just tried and it should definitely say 2.0.17 when building latest SDL git code (I tried building both with CMake and autotools/configure).

Building SDL2 should have created a `libSDL2-2.0.so.0.17.0` and a `libSDL2-2.0.so.0` that's a symlink to the former.
You can tell dhewm3 to use that lib by telling it to look in the directory that contains `libSDL2-2.0.so.0` with `LD_LIBRARY_PATH=/path/to/that/dir/ ./dhewm3`

**Comment by lucascoelho07** [comment]
I tried to build it again today but no success
I'm following the instructions on their wiki [](https://wiki.libsdl.org/Installation)
Could there be anything that I'm missing?

**Comment by DanielGibson** [comment]
There could, but I wouldn't know what because my crystal ball is currently used for xmas decoration and thus isn't available for its usual duty.

Can you try if this SDL2 build works on your system? [sdl2-amd64.tar.gz](https://github.com/dhewm/dhewm3/files/7621097/sdl2-amd64.tar.gz)

**Comment by DanielGibson** [comment]
SDL2 2.0.18 has been released recently, in case that helps

**Comment by DanielGibson** [comment]
What exactly do you mean with "sens 0.74"? How do you set it?
How do you set the 1600DPI?

**Comment by DanielGibson** [comment]
...

**Comment by Ch0wW** [comment]
Looks like as of today, the problem still isn't fixed unless some CVARs has to be inputted.

Using a Logitech G402, DPI of 4000, with a refresh rate of 1000Hz on Windows 10, if I'm repeatedly moving the camera from left to right very quickly, the camera will be unable to turn until I'll remove the mouse again. 

FPS doesn't seem to lower. Using a low sensitivity does help in seeing the issue better. Using a Linux distribution doesn't change the issue as well.

From what i've seen, problem is triggered on Dhewm 1.51 as well. It doesn't even happen a single time with the original Doom 3 binaries.
