### ISSUE TITLE
Request:  Is Controller Support Possible?

### ISSUE THREAD

**Issue by Big-the-Fat** [dhewm/dhewm3#536]
I can't play with mouse and keyboard for more than a few minutes these days.  I can only properly play games with a controller.  I would love to play Dhewm3 but I have to use Doom 3 BFG.  

I would consider this an accessibility issue. :)

**Comment by DanielGibson** [comment]
Yeah, it has been on my Todo list for a long time.. I hope to get around to it eventually ;)

**Comment by Big-the-Fat** [comment]
Thank you. :)

**Comment by RinMaru** [comment]
really would be an amazing edition allowing me to get rid of BFG one and for all.

**Comment by ViperAcidZX** [comment]
I'm curious: could rumble support be implemented too if this gets controller support one day?

**Comment by DanielGibson** [comment]
I'm currently working on gamepad support in this branch: https://github.com/dhewm/dhewm3/tree/controller-input

It already mostly works, but still has some issues, esp. in multiplayer.

I don't have any plans to work on rumble support, and I'm not sure how to implement it anyway (where/how to get the information when to rumble), but if someone figures it out: patches/pull requests are welcome ;)

**Comment by DanielGibson** [comment]
I think it's not pretty much ready. I'll upload Windows-Binaries for testing later, if you build yourself anyway you can use the current state of the aforementioned branch.

**Comment by DanielGibson** [comment]
Here's a build for Windows: [dhewm3-1.5.3pre-gamepad.zip](https://github.com/dhewm/dhewm3/files/13968587/dhewm3-1.5.3pre-gamepad.zip)

**Comment by wof8317** [comment]
Just tested on my PS3 controller. I loved how the game displayed the proper name of the buttons like Cross, Triangle, etc. Stick navigation in the menus was smooth and easy. Unless you need to polish the controller code more, I'd say that it is ready to ship.

**Comment by DanielGibson** [comment]
Great, thanks a lot for testing!

> I loved how the game displayed the proper name of the buttons like Cross, Triangle

Yeah, today I found out that SDL2 (from 2.0.12 on) supports detecting the kind of gamepad, so implementing this was easy enough.

I guess I'll merge it in a few days, I hope I'll get some more feedback in the meantime :)

**Comment by DanielGibson** [comment]
Note: I did some small improvements for the displayed button names, especially with Nintendo-like controllers, which aren't in the windows build linked above.

Please test the build anyway, as this is a pretty cosmetic change.

**Comment by DanielGibson** [comment]
As you have a DS4 controller: What button is detected as "Pad Back"? The "Share" button, I guess?

**Comment by Big-the-Fat** [comment]
Yeah, the "Share" button is detected (and named) "PAD_Back" when setting the button to an action in the bindings menu.

Just a thought, muscle memory causes me to hit 'fire' (in my case Right Shoulder) to confirm things in-menu but the game only recognises the "A" button.  Dunno if I'm just being weird or not.  Just thought perhaps whatever button is assigned to "fire" could also be used as a confirm button just like when in-game.  Hope that makes sense.  I have a habit of typing a lot of words and not really conveying what I mean!

Regardless, I'm super thankful that I can finally play Doom 3 with proper controller support. :)

**Comment by DanielGibson** [comment]
Isn't fire usually right trigger?

Not sure if I can make it use whatever button is bound to fire, the menu is pretty independent of the key binding system. I could make right trigger behave like Pad A (or left mouse button) though.

Also note that ingame GUIs, including the PDA, *do* you the fire button (whichever it is) for clicking, just the main menu and similar don't.

**Comment by Big-the-Fat** [comment]
No worries.  Yeah, it's usually the right trigger, I just prefer the click of the shoulder buttons.

Regarding the PDA, yeah, that's the reason why my muscle memory goes for the 'fire' button.

Like I say, it was just a thought.  I don't think it would be a big deal for anyone else.  I'm just a bit of a weirdo! :P

**Comment by DanielGibson** [comment]
nevermind, turns out using the attack button is easy enough!

**Comment by Big-the-Fat** [comment]
Oh cool beans.  Thanks for your kindness. :)

**Comment by DanielGibson** [comment]
Updated build for Windows: [dhewm3-1.5.3pre-gamepad2.zip](https://github.com/dhewm/dhewm3/files/13981022/dhewm3-1.5.3pre-gamepad2.zip)

**Comment by brad86m** [comment]
Controller is awesome. Thank you for this.

Messed with the seta joy_ commands a bit to get a good acceleration for turning, and it's great.

**Comment by DanielGibson** [comment]
I created gamepad configs for the base game and d3xp (Resurrection of Evil), based on the standard bindings of Doom3 BFG: [gamepad_cfgs.zip](https://github.com/dhewm/dhewm3/files/13996539/gamepad_cfgs.zip)
Put them in your base/ and d3xp/ folders, for the base game, open the console and enter `exec gamepad.cfg`, and for d3xp, do the same with `exec gamepad-d3xp.cfg`.
While the bindings are set immediately, you may have to restart dhewm3 for them to show up in the "Controls" menu.

The control scheme is like this (assuming an XBox-style gamepad):
* Left Stick: Move
  - Press Left Stick: Sprint
* Right Stick: Look around
  - Press Right stick: Crouch 
* A: Jump
* X: Reload
* Right Trigger: Attack
* Left Trigger: Flashlight
* Left Shoulder Button: Previous Weapon
* Right Shoulder Button: Next Weapon
* DPad Up: Grenade
* DPad Down: BFG
* DPad Left: Soulcube
* DPad Right: Fists/Grabber
* Back: PDA
* Start: Open/Close Menu (just like the Escape key)

Buttons "B" and "Y" are unused - in D3BFG, Y was "use", but no such button exists in Vanilla Doom3, and "B" seemed to be entirely unused in D3BFG (except in menus), for whatever reason. But you can of course bind them yourself to whatever you like ;)

**Comment by DanielGibson** [comment]
from the original manual (https://archive.org/details/xboxmanual_Doom_3_Collectors_Edition/page/n3/mode/2up) 
![doom3-og-xbox](https://github.com/dhewm/dhewm3/assets/1216493/d903d355-7b05-4652-812c-aaf1caaf1b3d)

not overly useful for modern gamepads, IMO

**Comment by IlDucci** [comment]
I'm trying to test this with a DualShock 4, but so far I can't move the camera with the right stick. How can I restart the setup so I can see if my config is breaking things or this mod?

Also, on a bit of a different subject, are you planning on adding assets to the game to include button icons or localized texts for the button names?

**Comment by DanielGibson** [comment]
For the right stick to work, you need to bind Turn Left, Turn Right and Look Up and Look Down accordingly

> Also, on a bit of a different subject, are you planning on adding assets to the game to include button icons or localized texts for the button names?

No

**Comment by ViperAcidZX** [comment]
I tried the controller support test build that was shared and so far it has worked pretty good with an official Xbox Series Controller and I tried hotplugging from swapping that controller out for the 8BitDo (in XInput mode) and it works pretty flawlessly with that one, I might have to do some more testing with other controllers I have access to. I do have some issues with navigation in the PDA screen. The simulated mouse controls work fine but I feel it's kinda slow in the PDA screen, even when tilting the stick all the way, and there's also the issue of having to use the simulated mouse to move a scroll bar down for long e-mail messages. I don't know if it can be implemented, but is there a way to have a joy CVAR command for scrolling up/down? Apart from the lack of rumble support, it is working out nice from what I experienced using the original Xbox controls; I might mess around and try to recreate the BFG Edition/Doom 3 (2019) controllers with this build of dhewm 3.

**Comment by DanielGibson** [comment]
Sorry, but the way the PDA is implemented just sucks, so it's very hard to improve. That's why the mousewheel doesn't work in the PDA either, even though it works in regular menus..

**Comment by IlDucci** [comment]
I think it reads alright, but you should also add the mappings in simple text format (just copypaste this part: https://github.com/dhewm/dhewm3/issues/536#issuecomment-1901723506 ) for people like me, who thought could just copypaste the files and run the EXE without running the command, thinking the game would get those cfg files automatically. You know, making it a bit more dumb-proof.

**Comment by DanielGibson** [comment]
Merged gamepad support into the main branch and added the default mappings configuration as suggested:
https://github.com/dhewm/dhewm3/blob/master/Configuration.md#using-gamepads

As this is merged, I'll close this issue, but if you have further remarks feel free to add them here; however if you find **actual bugs** (or something that is so annoying that I should change it) please *create a new issue* for that.

**Comment by ViperAcidZX** [comment]
> from the original manual ![d3xbox_manual_screenshot](https://github.com/dhewm/dhewm3/assets/19318128/5c721b31-2446-4e63-8a78-489d259e8af5)
> 
> not overly useful for modern gamepads, IMO (AFAIK "quick weapon select" allowed you to bind your 4 favorite weapons to the DPad - you can do that in dhewm3 in the normal controls menu)

I happen to have the original Xbox port of Doom 3 and playing it through backwards compatibility, I found in the Options menu under the Buttons configuration, the **ALTERNATIVE** button layout on an Xbox 360 controller translates pretty well on newer modern controllers since the Xbox's White and Black buttons are moved to LB and RB (or similar) respectively, and in my opinion works better for original Doom 3 than the BFG Edition-styled layout since the Sprint button is consistent with the other classic Doom games and the flashlight mechanics of original Doom 3 works in its favor. For reference, I took photos of the button and stick configurations of the game that can be found in [this album](https://freeimage.host/a/doom-3-xbox-stick-and-button-presets.AAMhP) (sorry for the poor picture quality, I don't have a camera on me that's up with the times).

I put together some pre-made gamepad config files. These include a modern-styled layout that is based on the Alternative configuration, a slightly tweaked BFG Edition configuration, and the original Xbox version's Default and Alternative configuration for those who want to try them out a Hyperkin Xbox Duke Controller.

[dhewm3_v1.5.3_gamepad_configs.zip](https://github.com/dhewm/dhewm3/files/14154509/dhewm3_v1.5.3_gamepad_configs.zip)

**Comment by DanielGibson** [comment]
which one is the "Alternative" layout on the screenshots? "Expert"? "Legacy"?

**Comment by ViperAcidZX** [comment]
The "Alternative" button layout is this one: https://freeimage.host/i/buttons-alternative.JlZ0iox

**Comment by DanielGibson** [comment]
Thanks, for some reason the linked album doesn't show that image.
BTW, you don't need to use weird image hosting sites, Github comments allow attaching images directly, see 
![image](https://github.com/dhewm/dhewm3/assets/1216493/901f9bea-a347-4434-9726-0775fea3a36a)

**Comment by DanielGibson** [comment]
I just released 1.5.3 RC1 - testing is welcome! :)
https://github.com/dhewm/dhewm3/releases/tag/1.5.3_RC1

**Comment by ViperAcidZX** [comment]
I've updated and fix the configurations I put together for dhewm3, apologizes for the inconvenience when using them with Resurrection of Evil/The Lost Mission expansions with some misplaced buttons.

[dhewm3_v1.5.3_gamepad_configs_v1.1..zip](https://github.com/dhewm/dhewm3/files/14174232/dhewm3_v1.5.3_gamepad_configs_v1.1.zip)

**Comment by DanielGibson** [comment]
Cool, thanks, I'll add a link to the documentation!

**Comment by DanielGibson** [comment]
https://github.com/dhewm/dhewm3/blob/master/Configuration.md#using-gamepads now has a link to your comment with the alternative configs, thanks again! :)

**Comment by ViperAcidZX** [comment]
Thank you as well!

**Comment by ViperAcidZX** [comment]
Minor issue, but on a V1 DualShock 4, the touchpad button doesn't seem to work nor mappable to anything I tried. Haven't tested on a V2 controller yet.

**Comment by ViperAcidZX** [comment]
Anyone having problems where out of nowhere the bottom face button stops working as a gamepad button and suddenly acts like Left Mouse Button? I had this happen at least 3 times already with RC1 of 1.5.3, and I tried forcibly unbinding the button face button (which in my case happens to be the A button on an Xbox controller) which didn't solve the problem. I've been experiencing this problem from a 64-bit build I compiled with the most recent commits of dhewm3. I also had the Enhanced Edition mod and HD Essentials Pack installed when this happened but I also encountered this problem without any mods installed. I have the recent log files from my play session if that might help isolate the cause of the issue.

[dhewm3log.txt](https://github.com/dhewm/dhewm3/files/14441460/dhewm3log.txt)
[stderr.txt](https://github.com/dhewm/dhewm3/files/14441461/stderr.txt)

> > Minor issue, but on a V1 DualShock 4, the touchpad button doesn't seem to work nor mappable to anything I tried. Haven't tested on a V2 controller yet.
> 
> Not sure the touchpad is recognized on any controller.
There are some games I have tried, even without SDL2 support used for some of them, that works with the Touchpad button.

**Comment by DanielGibson** [comment]
Argh, I knew this code was gonna bite me in the ass :-/
https://github.com/dhewm/dhewm3/blob/0d4405bbe62e3c304d6aa7e81f0449d0bc8cca34/neo/sys/events.cpp#L1012-L1027

I think I can reproduce the issue, and it seems to happen when switching from one ingame panel to another so quick that the first one doesn't get "deactivated" when activating the second, so when leaving the second only that one gets deactivated and my ugly hack thinks that one ingame GUI is still active..

And the problem is, it *can* happen that two ingame GUIs are active at the same time (or rather, that one needs to "remember" the old one when a new one becomes active), because the PDA is implemented in such an ugly way that it looks to my detection logic like just another ingame GUI (like a panel). So when a normal panel is active and the PDA is opened, the panels UI must remain in my list, so after closing the PDA the gamepad still works with it (as it only becomes inactive when moving the cursor away from it).

Not sure yet how to fix this, but at least I can reproduce the problem.. so thanks for reporting :)

**Comment by DanielGibson** [comment]
I think I fixed the bug, can you try the new build: [dhewm3-1.5.3_RC2_win32.zip](https://github.com/dhewm/dhewm3/files/14626099/dhewm3-1.5.3_RC2_win32.zip)

Note that it only properly fixes the bug in the base game and Resurrection of Evil, for the mods I'll have to adjust their DLLs as well (I'll do that before the proper 1.5.3 release).


I hope I get around to properly release 1.5.3 RC2 soon, but for now here's a Windows build, based on the code currently in the git master branch..

**Comment by DanielGibson** [comment]
Now there's also updated mod DLLs: https://github.com/dhewm/dhewm3/releases/tag/1.5.3_RC2

testing is very welcome!

**Comment by ViperAcidZX** [comment]
I tried Lost Mission with the RC2 release of v1.5.3 at the same spot I was having the problems I reported earlier and it still happens sadly. Even compiled 64-bit builds I compiled via source code reproduces the issue. I haven't tried base Doom 3 or Resurrection of Evil yet though.

**Comment by DanielGibson** [comment]
I'll take a look at D3LE, thanks!

(I reproduced the issue in Delta Labs 1 and I think I fixed what caused it there, I assumed that it would be the same problem in D3LE so I didn't test that :-/)

**Comment by DanielGibson** [comment]
I opened an extra issue for this: #566

**Comment by DanielGibson** [comment]
(in #556 you can also find an updated build that fixes this issue)
