### ISSUE TITLE
Low Fps with map UAC Franchise 666

### ISSUE THREAD

**Issue by walikor** [dhewm/dhewm3#651]
hi, I was trying some doom 3 maps like zombie_shuffle (works perfectly) and UAC Franchise 666, which unfortunately as soon as map 6661 starts the frame rate drops to 4 fps and gives errors on the console.
This is the map: https://www.moddb.com/games/doom-iii/addons/uac-franchise-666
and this is the image.
with vanilla doom 3 work well.
![Image](https://github.com/user-attachments/assets/7f0c8445-ed51-45e6-bce6-5911d1331103)

**Comment by DanielGibson** [comment]
> with vanilla doom 3 work well.

does this mean that this warning isn't printed in vanilla doom3, or just that it runs at a higher framerate?

For a higher framerate it often helps to disable soft particles and reduce anti-aliasing (esp. 16x is very demanding even on todays hardware)

Also: what operating system are you using, what hardware, what version of dhewm3?
All that text that is in the issue report form when creating a new issue is there for a reason...

**Comment by walikor** [comment]
> > with vanilla doom 3 work well.
> 
> does this mean that this warning isn't printed in vanilla doom3, or just that it runs at a higher framerate?
> 
> For a higher framerate it often helps to disable soft particles and reduce anti-aliasing (esp. 16x is very demanding even on todays hardware)
> 
> Also: what operating system are you using, what hardware, what version of dhewm3? All that text that is in the issue report form when creating a new issue is there for a reason...

exactly with doom 3 vanilla I don't have those errors in the console (no valid point found) and the framerate remains at 62, I disabled the soft particles and set the anisotropic filter to 1x but it didn't work, I'm using:
-windows 10 22H2
-Intel i5 8500 (6 cores 6 threads)
-32GB Ram DDR4
-NVIDIA GeForce RTX 4070 SUPER
-Dhewm3 Version 1.5.4

**Comment by DanielGibson** [comment]
I can reproduce this now (only on Windows, for whatever reason), I'm investigating...

**Comment by DanielGibson** [comment]
See https://github.com/dhewm/dhewm3/pull/652 for a fix, please test :)

**Comment by walikor** [comment]
> See [#652](https://github.com/dhewm/dhewm3/pull/652) for a fix, please test :)

hi, I tested with both the 32 bit and 64 version and they work correctly, without drops in fps or errors in the console.
Thanks.

**Comment by DanielGibson** [comment]
thanks for testing, I merged the fix

**Comment by DanielGibson** [comment]
> This was an odd bug.

Indeed - thankfully it could be reproduced in (Win32) debug builds, this is the kind of bug that sometimes only happens in optimized release builds, which makes debugging a lot harder.

**Comment by inf78** [comment]
Sadly, there is still a problem with this mod in not only the first map, but it seems to be present in all maps with fire extinguisher in it.
Just try to shoot off its glass casing. Performance gets to slideshow levels, at least in the Win32 1.5.5 RC2.
Console has this line when it happens:
`WARNING: idPhysics_RigidBody::SetClipModel: invalid mass for entity 'func_fracture_5' type 'idBrittleFracture'`

I also tested the latest Win64 test build (a93e50f) and here it doesn't get to the terrible performance stage at all, it just crashes with assertion failed.

I don't have an access to the Linux machine now, but I am sure that there were no performance problems when playing in a version built from source somwhere in August 2025. Perhaps there isn't any problem with a Linux version at all, I can't test now.

**Comment by DanielGibson** [comment]
what assertion fails? can you post the whole error?

**Comment by inf78** [comment]
Here is the error window. It's right after shooting the glass casing on start of the 6661 map.

![Image](https://github.com/user-attachments/assets/cff2ee79-fc7a-4103-84e3-4e032b73f283)
